#!/usr/bin/env python3
# Bake 16 emote PNGs (with transparency) into C++ byte arrays linked
# into the AltirraSDL binary.  Decoding is deferred to runtime via
# SDL3_image so the wire format stays PNG (smaller than raw RGBA).
#
# Reads:
#   <assets_dir>/icon01.png ... icon16.png
#
# Emits:
#   <out_dir>/emotes_data.h    — declarations
#   <out_dir>/emotes_data.cpp  — 16 byte arrays + index table
#
# Uses Python stdlib only.

import os
import sys


EMOTE_COUNT = 16


def write_bytes_array(lines, name, data):
    lines.append(f"static const uint8_t {name}[{len(data)}] = {{")
    chunk = []
    for i, b in enumerate(data):
        chunk.append(f"0x{b:02x},")
        if (i + 1) % 16 == 0:
            lines.append("    " + " ".join(chunk))
            chunk = []
    if chunk:
        lines.append("    " + " ".join(chunk))
    lines.append("};")


def main(argv):
    if len(argv) < 3:
        sys.stderr.write("usage: bake_emotes.py <out_dir> <assets_dir>\n")
        return 2

    out_dir = argv[1]
    assets_dir = argv[2]

    os.makedirs(out_dir, exist_ok=True)

    blobs = []
    for i in range(1, EMOTE_COUNT + 1):
        path = os.path.join(assets_dir, f"icon{i:02d}.png")
        with open(path, "rb") as f:
            data = f.read()
        if data[:8] != b"\x89PNG\r\n\x1a\n":
            raise ValueError(f"{path}: not a PNG file")
        blobs.append(data)
        print(f"icon{i:02d}.png: {len(data)} bytes")

    # --- Header ---
    header_path = os.path.join(out_dir, "emotes_data.h")
    hlines = [
        "// Auto-generated by tools/bake_emotes.py - do not edit.",
        "#pragma once",
        "#include <stdint.h>",
        "#include <stddef.h>",
        "",
        "#ifdef __cplusplus",
        'extern "C" {',
        "#endif",
        "",
        f"#define kATEmoteCount {EMOTE_COUNT}",
        "",
        "struct ATEmoteBlob {",
        "    const uint8_t *data;",
        "    size_t size;",
        "};",
        "",
        "extern const struct ATEmoteBlob kATEmoteBlobs[kATEmoteCount];",
        "",
        "#ifdef __cplusplus",
        "}",
        "#endif",
        "",
    ]
    tmp = header_path + ".tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        f.write("\n".join(hlines))
    os.replace(tmp, header_path)

    # --- Source ---
    source_path = os.path.join(out_dir, "emotes_data.cpp")
    slines = [
        "// Auto-generated by tools/bake_emotes.py - do not edit.",
        '#include "emotes_data.h"',
        "",
    ]
    for i, data in enumerate(blobs, start=1):
        write_bytes_array(slines, f"kEmote{i:02d}_PNGData", data)
        slines.append("")

    slines.append(f"const struct ATEmoteBlob kATEmoteBlobs[{EMOTE_COUNT}] = {{")
    for i, data in enumerate(blobs, start=1):
        slines.append(
            f"    {{ kEmote{i:02d}_PNGData, {len(data)} }},"
        )
    slines.append("};")
    slines.append("")

    tmp = source_path + ".tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        f.write("\n".join(slines))
    os.replace(tmp, source_path)

    print(f"Wrote {header_path}")
    print(f"Wrote {source_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
