#!/usr/bin/env python3
# Bake window/taskbar icon data into a C header + Windows .ico.
#
# Reads the Android launcher PNGs (the only icon art in the tree) and
# emits:
#
#   <outdir>/altirra_icon_data.h   — decoded RGBA8 byte arrays + sizes,
#                                    consumed by main_sdl3.cpp to build
#                                    SDL_Surface icons at runtime.
#   <outdir>/altirra.ico           — PNG-embedded .ico (Vista+), wired
#                                    into AltirraSDL.rc on Windows for
#                                    the exe/taskbar icon.
#
# Uses Python stdlib only (zlib, struct, binascii) so it runs on every
# GitHub-hosted runner (Linux/macOS/Windows) without pip installs.
# Supports exactly the PNG flavour the Android assets use: 8-bit RGBA,
# non-interlaced, color type 6. That's all we need — no generality.

import os
import struct
import sys
import zlib


PNG_SIGNATURE = b"\x89PNG\r\n\x1a\n"


def decode_png_rgba8(path):
    """Return (width, height, rgba_bytes) for an 8-bit RGBA non-interlaced PNG."""
    with open(path, "rb") as f:
        data = f.read()

    if data[:8] != PNG_SIGNATURE:
        raise ValueError(f"{path}: not a PNG file")

    pos = 8
    width = height = 0
    bit_depth = color_type = interlace = -1
    idat = bytearray()

    while pos < len(data):
        (length,) = struct.unpack(">I", data[pos:pos + 4])
        ctype = data[pos + 4:pos + 8]
        cdata = data[pos + 8:pos + 8 + length]
        pos += 8 + length + 4  # skip CRC

        if ctype == b"IHDR":
            (width, height, bit_depth, color_type,
             _comp, _filt, interlace) = struct.unpack(">IIBBBBB", cdata)
        elif ctype == b"IDAT":
            idat += cdata
        elif ctype == b"IEND":
            break

    if bit_depth != 8 or color_type != 6 or interlace != 0:
        raise ValueError(
            f"{path}: expected 8-bit RGBA non-interlaced PNG "
            f"(got depth={bit_depth}, color_type={color_type}, "
            f"interlace={interlace})")

    raw = zlib.decompress(bytes(idat))
    stride = width * 4
    out = bytearray(stride * height)
    prev = bytes(stride)
    ri = 0  # read index in `raw`
    wi = 0  # write index in `out`

    for _y in range(height):
        filt = raw[ri]
        ri += 1
        row = bytearray(raw[ri:ri + stride])
        ri += stride

        if filt == 0:  # None
            pass
        elif filt == 1:  # Sub
            for x in range(4, stride):
                row[x] = (row[x] + row[x - 4]) & 0xFF
        elif filt == 2:  # Up
            for x in range(stride):
                row[x] = (row[x] + prev[x]) & 0xFF
        elif filt == 3:  # Average
            for x in range(stride):
                left = row[x - 4] if x >= 4 else 0
                row[x] = (row[x] + ((left + prev[x]) >> 1)) & 0xFF
        elif filt == 4:  # Paeth
            for x in range(stride):
                a = row[x - 4] if x >= 4 else 0
                b = prev[x]
                c = prev[x - 4] if x >= 4 else 0
                p = a + b - c
                pa = abs(p - a)
                pb = abs(p - b)
                pc = abs(p - c)
                if pa <= pb and pa <= pc:
                    pr = a
                elif pb <= pc:
                    pr = b
                else:
                    pr = c
                row[x] = (row[x] + pr) & 0xFF
        else:
            raise ValueError(f"{path}: unknown PNG filter {filt}")

        out[wi:wi + stride] = row
        wi += stride
        prev = bytes(row)

    return width, height, bytes(out)


def write_header_and_source(header_path, source_path, entries):
    """Emit a declarations header + a definitions .c file.

    Split is deliberate: the RGBA arrays are ~1 MB total. Keeping them
    in a dedicated .c translation unit means only that one TU recompiles
    on icon changes — main_sdl3.cpp just sees tiny extern declarations.

    entries = [(size, rgba_bytes), ...], sorted largest-first.
    """
    # --- header ---
    hlines = []
    hlines.append("// Auto-generated by tools/bake_icon.py — do not edit.")
    hlines.append("#pragma once")
    hlines.append("#include <stdint.h>")
    hlines.append("#include <stddef.h>")
    hlines.append("")
    hlines.append("#ifdef __cplusplus")
    hlines.append('extern "C" {')
    hlines.append("#endif")
    hlines.append("")
    hlines.append("struct ATBakedIcon {")
    hlines.append("    int size;              // width == height in pixels")
    hlines.append("    const uint8_t* rgba;   // size*size*4 bytes, row-major")
    hlines.append("};")
    hlines.append("")
    hlines.append("extern const struct ATBakedIcon kAltirraIcons[];")
    hlines.append("extern const size_t kAltirraIconCount;")
    hlines.append("")
    hlines.append("#ifdef __cplusplus")
    hlines.append("}")
    hlines.append("#endif")
    hlines.append("")

    tmp = header_path + ".tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        f.write("\n".join(hlines))
    os.replace(tmp, header_path)

    # --- source ---
    slines = []
    slines.append("// Auto-generated by tools/bake_icon.py — do not edit.")
    slines.append('#include "altirra_icon_data.h"')
    slines.append("")

    for size, rgba in entries:
        sym = f"kAltirraIconRGBA_{size}"
        slines.append(f"static const uint8_t {sym}[{len(rgba)}] = {{")
        chunk = []
        for i, b in enumerate(rgba):
            chunk.append(f"0x{b:02x},")
            if (i + 1) % 16 == 0:
                slines.append("    " + " ".join(chunk))
                chunk = []
        if chunk:
            slines.append("    " + " ".join(chunk))
        slines.append("};")
        slines.append("")

    slines.append("const struct ATBakedIcon kAltirraIcons[] = {")
    for size, _ in entries:
        slines.append(f"    {{ {size}, kAltirraIconRGBA_{size} }},")
    slines.append("};")
    slines.append(f"const size_t kAltirraIconCount = {len(entries)};")
    slines.append("")

    tmp = source_path + ".tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        f.write("\n".join(slines))
    os.replace(tmp, source_path)


def write_ico(out_path, png_paths_by_size):
    """Build a PNG-embedded .ico (Vista+).

    Entries whose pixel dimension >= 256 must encode their size byte as 0.
    We embed the original PNG bytes directly — no re-encoding needed.
    """
    sizes = sorted(png_paths_by_size.keys())
    count = len(sizes)

    header = struct.pack("<HHH", 0, 1, count)  # reserved, type=icon, count
    directory = b""
    images = b""
    offset = 6 + count * 16  # ICONDIR + N * ICONDIRENTRY

    for size in sizes:
        with open(png_paths_by_size[size], "rb") as f:
            png_bytes = f.read()
        size_byte = 0 if size >= 256 else size
        directory += struct.pack(
            "<BBBBHHII",
            size_byte,         # width
            size_byte,         # height
            0,                 # palette count (0 for truecolor)
            0,                 # reserved
            1,                 # color planes
            32,                # bits per pixel
            len(png_bytes),    # bytes in resource
            offset,            # offset from start of file
        )
        images += png_bytes
        offset += len(png_bytes)

    tmp = out_path + ".tmp"
    with open(tmp, "wb") as f:
        f.write(header + directory + images)
    os.replace(tmp, out_path)


def main(argv):
    if len(argv) < 3:
        sys.stderr.write(
            "usage: bake_icon.py <out_dir> <png> [<png> ...]\n")
        return 2

    out_dir = argv[1]
    png_paths = argv[2:]

    os.makedirs(out_dir, exist_ok=True)

    decoded = []       # (size, rgba_bytes)
    by_size_path = {}  # size -> source path (for .ico)
    for path in png_paths:
        w, h, rgba = decode_png_rgba8(path)
        if w != h:
            raise ValueError(f"{path}: icon must be square ({w}x{h})")
        decoded.append((w, rgba))
        by_size_path[w] = path

    decoded.sort(key=lambda e: -e[0])  # largest first — primary icon

    write_header_and_source(
        os.path.join(out_dir, "altirra_icon_data.h"),
        os.path.join(out_dir, "altirra_icon_data.cpp"),
        decoded,
    )
    write_ico(os.path.join(out_dir, "altirra.ico"), by_size_path)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
